name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20, 22]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run test
        run: pnpm test

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: ${{ matrix.node == 22 && matrix.os == 'ubuntu-latest' }}
        with:
          result-type: lines
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/jbaubree/49ef05b87cfb759d72800c33a6ead310
          upload-badge: ${{ github.base_ref == 'refs/heads/main' }}

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-20, ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint
